config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/storer', to: 'pages#storer'
  get '/forum', to: 'pages#forum'
  get '/forumpost', to: 'pages#forum_post'
  get '/browse_wanted', to: 'buy_adverts#browse_buy'
  get '/browse_for_sale', to: 'sell_adverts#browse_sell'
  get '/browse_storage_space', to: 'storage_spaces#browse_storage_space'
  # mount Thredded::Engine => '/forum'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'user/dashboard', to: 'users#dashboard', as: 'user_dashboard'
  post 'sell_adverts/:sell_advert_id/send_email', to: 'sell_adverts#send_contact_email', as: 'send_contact_email'

  resources :storage_spaces do
    resources :reviews, only: [:new, :create, :edit, :update]
  end

  resources :reviews, only: [:destroy]

  resources :storage_spaces do
    resources :bookings, except: [:destroy]
  end

  resources :sell_adverts, path: 'for-sale' do
    resources :orders, except: [:destroy]
  end

  resources :buy_adverts, path: 'wanted'
  resources :search, only: [:index]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # after_create :send_welcome_email

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :storage_spaces
  has_many :bookings
  has_many :buy_adverts
  has_many :sell_adverts
  has_many :reviews
  after_create :get_username

  def get_username
    self.username = self.email.split("@")[0]
  end

  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
  def dashboard
    @user = current_user
    @storage_spaces = @user.storage_spaces
    @booking_for_my_storage = Booking.where(storage_space: @storage_spaces)
    @my_bookings = @user.bookings
    @buy_adverts = @user.buy_adverts
    @sell_adverts = @user.sell_adverts
  end
end

app/views/users/dashboard.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <div>
        <h3><%= current_user.username %> Dashboard</h3>
        <h6>First Name: <%= current_user.first_name %></h6>
        <h6>Last Name: <%= current_user.last_name %></h6>
        <h6>Email: <%= current_user.email %></h6>
        <div class="section-div-margin">
          <h4>Bookings</h4>
        </div>
        <div>
          <ul>
          <% current_user.bookings.each do |booking| %>
            <li>Storage Space Title: <%= link_to booking.storage_space.title, storage_space_booking_path(booking.storage_space_id, booking.id) %> Start Date: <%= booking.start_date %> End Date: <%= booking.end_date %> - <%= link_to "Leave a review", storage_space_booking_path(booking.storage_space_id, booking.id) %> - <%= link_to "Edit Booking", edit_storage_space_booking_path(booking.storage_space_id, booking.id) %></li>
          <% end %>
          </ul>
        </div>
      </div>

      <div>
        <div class="section-div-margin">
          <h4>Your Storage Spaces</h4>
          <%= link_to "Create new storage space", new_storage_space_path, class: "btn-medium" %>
          <%= link_to "All Storage", storage_spaces_path, class: "btn-medium" %>
        </div>
          <ul>
            <% current_user.storage_spaces.each do |space| %>
              <li>Storage Space Title: <%= space.title %> - <%= link_to "View Storage", storage_space_path(space) %> - <%= link_to "Edit Ad", edit_storage_space_path(space) %></li>
            <% end %>
          </ul>
      </div>
      <div>
        <div class="section-div-margin">
          <h4>Your Storage Spaces Bookings</h4>
        </div>
          <ul>
           <% @booking_for_my_storage.each do |booked| %>
                <li><%= booked.storage_space.title %> - storage space user/owner: <%= booked.storage_space.user.username %> - bookings owner: <%= booked.user.username %> - <%= link_to "View Booking", storage_space_booking_path(booked.storage_space_id, booked.id) %> - <%= link_to "Edit Booking", edit_storage_space_booking_path(booked.storage_space_id, booked.id) %></li>
            <% end %>
          </ul>
      </div>
      <div>
        <div class="section-div-margin">
          <h4>Your Sell Adverts</h4>
        <%= link_to "Place a Sell Ad", new_sell_advert_path, class: "btn-medium" %>
        </div>
          <ul>
           <% @sell_adverts.each do |sellads| %>
                <li><%= sellads.title %> - <%= link_to "View Ad", sell_advert_path(sellads) %> - <%= link_to "Edit Ad", edit_sell_advert_path(sellads) %> - <%= link_to "Delete Ad", sell_advert_path(sellads), method: :delete%></li>
            <% end %>
          </ul>
      </div>
            <div>
        <div class="section-div-margin">
          <h4>Your Buy Adverts</h4>
        <%= link_to "Place a Wanted Ad", new_buy_advert_path, class: "btn-medium" %>
        </div>
          <ul>
           <% @buy_adverts.each do |buyads| %>
                <li><%= buyads.title %> - <%= link_to "View Ad", sell_advert_path(buyads) %> - <%= link_to "Edit Ad", edit_sell_advert_path(buyads) %> - <%= link_to "Delete Ad", sell_advert_path(buyads), method: :delete%></li>
            <% end %>
          </ul>
      </div>
    </div>
  </div>
</div>