config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/storer', to: 'pages#storer'
  get '/forum', to: 'pages#forum'
  get '/forumpost', to: 'pages#forum_post'
  get '/browse_wanted', to: 'buy_adverts#browse_buy'
  get '/browse_for_sale', to: 'sell_adverts#browse_sell'
  get '/browse_storage_space', to: 'storage_spaces#browse_storage_space'
  # mount Thredded::Engine => '/forum'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'user/dashboard', to: 'users#dashboard', as: 'user_dashboard'
  post 'sell_adverts/:sell_advert_id/send_email', to: 'sell_adverts#send_contact_email', as: 'send_contact_email'

  resources :storage_spaces do
    resources :reviews, only: [:new, :create, :edit, :update]
  end

  resources :reviews, only: [:destroy]

  resources :storage_spaces do
    resources :bookings, except: [:destroy]
  end

  resources :sell_adverts, path: 'for-sale' do
    resources :orders, except: [:destroy]
  end

  resources :buy_adverts, path: 'wanted'
  resources :search, only: [:index]
end

app/models/storage_space.rb
class StorageSpace < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews
  validates :title, :description, :address, presence: true
  monetize :price_cents, allow_nil: true
  # validates :photo, presence: true
  mount_uploader :photo, PhotoUploader
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def self.search(params)
    sql_query = " \
      storage_spaces.title @@ :query \
      OR storage_spaces.description @@ :query \
    "
    StorageSpace.where(sql_query, query: "%#{params}%")
  end
end

app/controllers/storage_spaces_controller.rb
class StorageSpacesController < ApplicationController
  before_action :set_storage_space, only: [:show, :destroy, :edit, :update]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    if params[:query].present?
      sql_query = " \
        storage_space.title @@ :query \
        OR storage_space.description @@ :query \
      "
      @storage_spaces = StorageSpace.where(sql_query, query: "%#{params[:query]}%")
      @results = StorageSpace.where(sql_query, query: "%#{params[:query]}%")
    else
      @results = StorageSpace.all
      @storage_spaces = StorageSpace.all
    end
    # geocoder maps
    @storage_spaces = StorageSpace.where.not(latitude: nil, longitude: nil)
    @markers = @storage_spaces.map do |s|
      {
        lat: s.latitude,
        lng: s.longitude,
        # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
      }
      # @storage_spaces = policy_scope(StorageSpace).order(created_at: :desc)
    end
    @categories = Category.all
  end

  def show
    @markers = [
      {
        lat: @storage_space.latitude,
        lng: @storage_space.longitude
      }]
      # @storage_spaces = policy_scope(StorageSpace).order(created_at: :desc)
  end

  def new
    @storage_space = StorageSpace.new
    # authorize @storage_space
  end

  def create
    # authorize @storage_space
    @storage_space = StorageSpace.new(storage_space_params)
    @storage_space.user = current_user

    if @storage_space.save
      redirect_to storage_space_path(@storage_space), notice: 'Storage Space was successfully created.'
    else
      render :new, alert: 'Could not create the storage_space'
    end
  end

  def edit
  end

  def update
    # authorize @storage_space
    if @storage_space.update(storage_space_params)
      redirect_to @storage_space, notice: 'Storage Space was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    # authorize @storage_space
    @storage_space.destroy
    redirect_to root_path
  end

  def browse_storage_space
    @storage_spaces = StorageSpace.all
  end

  private

  def set_storage_space
    @storage_space = StorageSpace.find(params[:id])
    # authorize @storage_space
  end

  def storage_space_params
    params.require(:storage_space).permit(
      :title,
      :description,
      :address,
      :price,
      :photo)
  end
end

app/views/storage_spaces/_form.html.erb
<div class="container">
  <div class="row">
      <div>
        <%= simple_form_for @storage_space do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <%= f.input :title, required: true %>
        <%= f.input :description, required: false %>
        <%= f.input :address %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.input :price %>

        <%= f.button :submit, class: "btn btn-primary" %>
        <% end %>
      </div>
  </div>
</div>

app/views/storage_spaces/edit.html.erb
<%= content_for(:title) do %>
Edit Storage Space
<% end %>
<h5>Edit in the form and save your storage space</h5>
<%= render 'form', storage_space: @storage_space%>

app/views/storage_spaces/index.html.erb
<%= render 'shared/list' %>

<div
  id="map"
  style="width: 94%;
  height: 300px;
margin: 0 auto;
  margin-bottom: 60px;"
  data-markers="<%= @markers.to_json %>"
></div>

app/views/storage_spaces/new.html.erb
<%= content_for(:title) do %>
New Storage Space
<% end %>

<h5>Fill in the form and save your storage space</h5>
<%= render 'form', storage_space: @storage_space%>

app/views/storage_spaces/show.html.erb
<%= content_for(:title) do %>
<%= @storage_space.title %>
<% end %>

<div class="full-container">
  <div class="half-container col-sm-6">
    <div class="" style="display: flex; justify-content: space-between; flex-direction: column; height: 500px; width: 500px;">
      <div class="title text-left">
        <h2><%= @storage_space.title %></h2>
      </div>
      <div class="half-container" style="text-align: left">
        <p>Description:</p>
        <div class="textbox">
          <p><%=raw @storage_space.description %></p>
        </div>
        <p>Address:</p>
        <div class="textbox">
          <p><%= @storage_space.address %></p>
        </div>
        <div class="textbox price">
          <h5>Price:</h5>
          <h5><%= @storage_space.price %> <%= @storage_space.price.symbol %> / Per Day</h5>
        </div>
      </div>
      <%= link_to "Book this space!", new_storage_space_booking_path(@storage_space), class: "btn-medium" %>
      <div class="btn-medium-black" data-toggle="modal" data-target="#myModal">
        Send an email
      </div>
<!--       <div class="crud-action">
        <%= link_to "Edit", edit_storage_space_path, class: "btn-crud"%>
        <%= link_to "Delete ", storage_space_path(@storage_space), class: "btn-crud", method: :delete%>
      </div> -->
    </div>
  </div>

  <!-- tabs -->
  <div class="half-container col-sm-6">
    <div class="">
      <ul  class="nav nav-pills">
    		<li class="active"><a  href="#1b" data-toggle="tab">Images</a></li>
    		<li><a href="#2b" data-toggle="tab">Map</a></li>
        <li><a href="#3b" data-toggle="tab">Contact</a></li>
    	</ul>
			<div class="tab-content">
			  <div class="tab-pane active" id="1b">
          <% if @storage_space.photo.filename.nil? %>
          <div class="avatar-large">
            <i class="fas fa-camera-retro"></i>
            <%= link_to "", @storage_space, class: "advert-link" %>
          </div>
          <% else %>
            <%= cl_image_tag @storage_space.photo, :gravity=>"center", :height=>500, :crop=>"fill", :quality=>"auto", :fetch_format=>:auto %>
          <% end %>
				</div>
				<div class="tab-pane" id="2b">
          <div
            id="map"
            style="
            width: 100%;
            height: 500px;
            margin: 0 auto;"
            data-markers="<%= @markers.to_json %>"
          ></div>
  			</div>
         <div class="tab-pane" id="3b">
          <div class="title text-left title-space-storage-space-contact">
          <p>Name:</p>
          <div class="textbox-contact-storage-space">
            <p><%= @storage_space.user.first_name %> <%= @storage_space.user.last_name %></p>
          </div>
          <p>Batch number:</p>
          <div class="textbox-contact-storage-space margin-bottom-batch_number">
            <p>Test</p>
          </div>
           <p>Contact details:</p>
          <div class="textbox-contact-storage-space">
            <ul class="list-inline">
              <li><i class="fab fa-whatsapp"></i></li>
              <li><p><%= @storage_space.user.phone_number %></p></li>
            </ul>
            <ul class="list-inline">
              <li><i class="far fa-envelope-open"></i></li>
              <li><p><%= @storage_space.user.email %></p></li>
            </ul>
          </div>
          </div>
        </div>

			</div>
    </div>
  </div>
</div>

<!-- reviews -->

<div class="col-md-12">
  <h2>Reviews</h2>
  <div class="reviews-container">
    <% @storage_space.reviews[0..4].each do |review| %>
    <div class="review-container">
      <div class="review-box">
        <p><%= review.description %></p>
        <br>
        <ul class="list-inline stars box-stars">
          <% review.rating.times do %>
            <li><i class="fas fa-star";></i></li>
          <% end %>
        </ul>
        <div class="reviewer-name">
          <%= "#{review.user.first_name}" %>
        </div>
      </div>
    </div>
  <% end %>
  </div>
  <div class="collapse" id="collapseExample">
    <div class="reviews-container">
      <% @storage_space.reviews.drop(5).each do |review| %>
      <div class="review-container">
        <div class="review-box">
          <p><%= review.description %></p>
          <br>
          <ul class="list-inline stars box-stars">
            <% review.rating.times do %>
              <li><i class="fas fa-star";></i></li>
            <% end %>
          </ul>
          <div class="reviewer-name">
            <%= "#{review.user.first_name}" %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
  <div class="button-container text-left">
    <button id="morereviews" class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
      See More Reviews
    </button>
  </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Send email to <%= @storage_space.user.email %></h4>
      </div>
      <div class="modal-body">
        <%= form_tag send_contact_email_path(@storage_space), method: :post do |f| %>
          <%= text_area_tag :message, params[:message], placeholder: "Write your message",class: "form mail-form", rows: 10, cols: 25%>
          <input type="submit" id='email-submit'>
        <% end %>
      </div>
    </div>
  </div>
</div>