config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/storer', to: 'pages#storer'
  get '/forum', to: 'pages#forum'
  get '/forumpost', to: 'pages#forum_post'
  get '/browse_wanted', to: 'buy_adverts#browse_buy'
  get '/browse_for_sale', to: 'sell_adverts#browse_sell'
  get '/browse_storage_space', to: 'storage_spaces#browse_storage_space'
  # mount Thredded::Engine => '/forum'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'user/dashboard', to: 'users#dashboard', as: 'user_dashboard'
  post 'sell_adverts/:sell_advert_id/send_email', to: 'sell_adverts#send_contact_email', as: 'send_contact_email'

  resources :storage_spaces do
    resources :reviews, only: [:new, :create, :edit, :update]
  end

  resources :reviews, only: [:destroy]

  resources :storage_spaces do
    resources :bookings, except: [:destroy]
  end

  resources :sell_adverts, path: 'for-sale' do
    resources :orders, except: [:destroy]
  end

  resources :buy_adverts, path: 'wanted'
  resources :search, only: [:index]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_list.html.erb
<div id ="form-search-cont" style="margin-top: 25px">
  <%= render 'shared/search_form' %>
</div>

<div class="container">

<% if @results == [] %>
  <%= "Unfortunately there are no results. The good thing is the search is working." %>
<% else %>
<% previous_item = nil %>
<div class="row">
  <% @results.each do |result| %>


  <!-- type title -->
    <!-- <div class="container container-margin"> -->
      <% if previous_item.nil? || result.class.name != previous_item.class.name  %>
        <div style="margin-bottom: 30px">
          <% if result.class.name == "StorageSpace" %>
            <div class="container"></div>
            <!-- <div class="row"> -->
            <h3>STORAGE SPACES</h3>
          <% elsif result.class.name == "BuyAdvert" %>
            <div class="container"></div>
            <!-- <div class="row"> -->
            <h3>WANTED</h3>
          <% else %>
            <div class="container"></div>
            <!-- <div class="row"> -->
            <h3>FOR SALE</h3>
          <% end %>
        </div>
      <% end %>
    <!-- </div> -->

    <!-- advert -->

      <div class="col-xs-12 col-sm-4">
          <% if result.photo.filename.nil? %>
          <div class="avatar-large card-margin-top">
            <i class="fas fa-camera-retro"></i>
            <%= link_to "", result, class: "advert-link" %>
          </div>
          <% else %>
            <div class="card-margin-top">
              <!-- <%= cl_image_tag result.photo, :crop=>"scale", :quality=>"auto:eco", :fetch_format=>:auto, class: "card img-responsive" %> -->
              <!-- make pictures fill the space -->
              <div class="card"
              style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
              url('<%= cl_image_path result.photo, height: 300, width: 400, :quality=>"auto:eco", :fetch_format=>:auto, crop: :fill %>')">
              </div>
              <%= link_to "", result %>
            </div>
          <% end %>
        <div class="card-body-margin-top">
          <div class="place-name"><%= link_to "#{result.title}", result %></div>
          <div class="price"><%= result.price.symbol %> <%= result.price %></div>
        </div>
          <div class="item-adverts-footer card-margin-top">
            <div class="row card-row">
              <div class="item-adverts-footer-item item-adverts-footer-item-first">
                <div>
                  <h6>Posted by:</h6>
                </div>
                <div>
                  <p><%= result.user.username %></p>
                </div>
              </div>
              <div class="item-adverts-footer-item item-adverts-footer-item-border">
                <div>
                  <h6>Posted on:</h6>
                </div>
                <div>
                  <p><%= result.created_at.strftime("%d-%m-%Y") %></p>
                </div>
              </div>
              <div class="item-adverts-footer-item item-adverts-footer-item-border">
                <div>
                  <h6>Location:</h6>
                </div>
                <div>
                  <p><%= result.address ? "#{result.address}" : "?" %></p>
                </div>
              </div>
            </div>
          </div>
      </div>
    <!-- </div> -->
    <% previous_item = result %>
  <% end %>
<% end %>
</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <div class="navbar-logo-title">
    <div>
      <%= link_to root_path, class: "navbar-wagon-brand" do %>
        <%= image_tag "LWR-red.png", height: 50 %>
      <% end %>
    </div>

    <%= link_to root_path, class: "navbar-wagon-item navbar-wagon-link navbar-div-title" do%>
      <div class="navbar-title">
        <strong>Le Wagon Remains</strong>
      </div>
    <% end %>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <div>
          <%= link_to forum_path, class: "navbar-wagon-item navbar-wagon-link navbar-div" do%>
        <div>Forum</div>
        <% end %>
      </div>
      <div>
          <%= link_to storer_path, class: "navbar-wagon-item navbar-wagon-link navbar-div" do%>
        <div>Become a Storer</div>
        <% end %>
      </div>
      <div>
          <%= link_to new_storage_space_path, class: "navbar-wagon-item navbar-wagon-link navbar-div" do%>
        <div>Create Storage</div>
        <% end %>
      </div>

      <!-- Place Ad with dropdown menu -->
      <div class="navbar-wagon-item navbar-wagon-link navbar-div">
        <div class="dropdown">
          <a href="#" class="dropdown-toggle navbar-div" data-toggle="dropdown" role="button">Place Ad</a>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><%= link_to new_sell_advert_path do %>
                <%= t(".sell_advert", default: "Sell Advert") %>
              <% end %>
            </li>
            <li><%= link_to new_buy_advert_path do %>
                <%= t(".buy_advert", default: "Buy Advert") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "https://ui-avatars.com/api/?name=#{current_user.first_name}+#{current_user.last_name}&background=e2e2e2", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_dashboard_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".dashboard", default: "Dashboard") %>
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path(current_user) do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Edit Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>

      <!-- Login link (when logged out) -->
      <div>
        <%= link_to t(".sign_in", default: "Forum"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link navbar-div" %>
      </div>
      <div>
        <%= link_to t(".sign_in", default: "Messages"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link navbar-div" %>
      </div>
      <div>
        <%= link_to "Become a Storer", "#", class: "navbar-wagon-item navbar-wagon-link navbar-div" %>
      </div>
      <div>
        <%= link_to t(".sign_up", default: "Sign Up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link navbar-div" %>
      </div>
      <div>
         <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link navbar-div" %>
      </div>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_second.html.erb
<div class="navbar-wagon-second">
    <!-- Logo -->
  <div class="navbar-logo-title">
    <div>

    </div>


  </div>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
      <!-- Links when logged in -->
      <div>
          <%= link_to buy_adverts_path, class: "navbar-wagon-item-second navbar-wagon-link-second navbar-div-second" do%>
        <div>Wanted Ads</div>
        <% end %>
      </div>
      <div>
          <%= link_to sell_adverts_path, class: "navbar-wagon-item-second navbar-wagon-link-second navbar-div-second" do%>
        <div>For Sale Ads</div>
        <% end %>
      </div>
      <div>
          <%= link_to storage_spaces_path, class: "navbar-wagon-item-second navbar-wagon-link-second navbar-div-second" do%>
        <div>Storage Spaces</div>
        <% end %>
      </div>
  </div>
</div>

app/views/shared/_search_form.html.erb
<div class="searchbar">
  <%= form_tag search_index_path, method: :get, class: "searchbar-form" do |f| %>
  <div class="dropdown">
    <a id="dropdown" role="button" data-toggle="dropdown" class="btn btn-primary searchbar-home-button" href="#">
        Category <span class="caret"></span>
    </a>
    <ul class="dropdown-menu searchbar-dropdown" role="menu" aria-labelledby="dropdown">
      <li class="dropdown-cat" style="font-size: 16px;">
       <%= radio_button_tag(:categories, "All")%>
      <%= label_tag(:categories, "All")  %>
        </li>

      <% @categories.each do |c| %>
        <li class="dropdown-cat" style="font-size: 16px;">
          <%= radio_button_tag(:categories, c.name)%>
          <%= label_tag(:categories, c.name)  %>
        </li>
        <% end %>
    </ul>
  </div>

  <div>
    <ul class="list-inline" style="margin: 0; padding: 0; display: flex;">
      <li style="padding: 0;">
        <%= text_field_tag :query, params[:query], placeholder: "Find exactly what you need!", class: "form form-width searchbar-height"%>
      </li>
      <li style="padding: 0;">
        <input type="submit" class="searchbar-submit">
      </li>
    </ul>
  </div>
  <% end %>
</div>