config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/storer', to: 'pages#storer'
  get '/forum', to: 'pages#forum'
  get '/forumpost', to: 'pages#forum_post'
  get '/browse_wanted', to: 'buy_adverts#browse_buy'
  get '/browse_for_sale', to: 'sell_adverts#browse_sell'
  get '/browse_storage_space', to: 'storage_spaces#browse_storage_space'
  # mount Thredded::Engine => '/forum'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'user/dashboard', to: 'users#dashboard', as: 'user_dashboard'
  post 'sell_adverts/:sell_advert_id/send_email', to: 'sell_adverts#send_contact_email', as: 'send_contact_email'

  resources :storage_spaces do
    resources :reviews, only: [:new, :create, :edit, :update]
  end

  resources :reviews, only: [:destroy]

  resources :storage_spaces do
    resources :bookings, except: [:destroy]
  end

  resources :sell_adverts, path: 'for-sale' do
    resources :orders, except: [:destroy]
  end

  resources :buy_adverts, path: 'wanted'
  resources :search, only: [:index]
end

app/models/sell_advert.rb
class SellAdvert < ApplicationRecord
  belongs_to :user
  belongs_to :category
  belongs_to :subcategory
  has_one :order
  has_one :storage_space
  validates :condition, inclusion: { in: ["New", "Like-New", "Used"]}
  validates :title, :description, :address, :condition, presence: true
  monetize :price_cents, allow_nil: true
  # validates :photo, presence: true
  mount_uploader :photo, PhotoUploader

  def self.search(params)
    sql_query = " \
      sell_adverts.title @@ :query \
      OR sell_adverts.description @@ :query \
    "
    SellAdvert.where(sql_query, query: "%#{params}%")
  end
end

app/controllers/sell_adverts_controller.rb
class SellAdvertsController < ApplicationController
  before_action :set_sell_advert, only: [:show, :edit, :destroy, :update]

  def index
    if params[:query].present?
      sql_query = " \
        sell_adverts.title @@ :query \
        OR sell_adverts.description @@ :query \
        OR storage_space.title @@ :query \
        OR storage_space.description @@ :query \
      "
      @sell_adverts = SellAdvert.joins(:storage_space).where(sql_query, query: "%#{params[:query]}%")
      @results = SellAdvert.joins(:storage_space).where(sql_query, query: "%#{params[:query]}%")
    else
      @sell_adverts = SellAdvert.all
      @results = SellAdvert.all
    end
    @categories = Category.all
  end

  def show
  end

  def new
    @sell_advert = SellAdvert.new
  end

  def create
    @sell_advert = SellAdvert.new(sell_advert_params)
    @sell_advert.user = current_user

    if @sell_advert.save
      redirect_to sell_adverts_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @sell_advert.update(sell_advert_params)
      redirect_to @sell_advert
    else
      render :edit
    end
  end

  def destroy
    @sell_advert.destroy
    redirect_to root_path
  end

  def send_contact_email
    @sell_advert = SellAdvert.find(params[:sell_advert_id])
    @receiver = @sell_advert.user
    @sender = current_user
    @message = params[:message]
    UserMailer.message_user(@receiver, @sender, @message, @sell_advert).deliver
    redirect_to sell_advert_path(@sell_advert)
  end

  def browse_sell
     @sell_adverts = SellAdvert.all
  end

  private

  def set_sell_advert
    @sell_advert = SellAdvert.find(params[:id])
  end

  def sell_advert_params
    params.require(:sell_advert).permit(:title, :description, :condition, :price, :photo, :address, :category_id, :subcategory_id, :storage_space)
  end
end

app/views/sell_adverts/_form.html.erb
<div class="container">
  <div class="row">
      <div>
        <%= simple_form_for @sell_advert do |f| %>
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
          <%= f.input :title %>
          <%= f.input :description %>
          <%= f.input :address %>
          <%= f.input :condition, :collection => %w[New Like-New Used] %>
          <%= f.label :category_id %>
          <%= f.collection_select :category_id, Category.order(:name), :id, :name, include_blank: true %>
          <%= f.label :subcategory_id, "Subcategory" %>
          <%= f.grouped_collection_select :subcategory_id, Category.order(:name), :subcategories, :name, :id, :name, include_blank: true %>
          <%= f.input :price %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
          <%= f.button :submit, class: "btn btn-primary" %>
        <% end %>
      </div>
  </div>
</div>

app/views/sell_adverts/edit.html.erb
<%= content_for(:title) do %>
Edit For Sale Ad
<% end %>
<h1>SellAdverts#edit</h1>
<p>Find me in app/views/sell_adverts/edit.html.erb</p>
<%= render 'form', sell_advert: @sell_advert%>

app/views/sell_adverts/index.html.erb
<%= render 'shared/list' %>

app/views/sell_adverts/new.html.erb
<%= content_for(:title) do %>
What would you like to sell?
<% end %>

<div style="text-align: center; margin-top: 30px; margin-bottom: -30px;">
<h3>What would you like to sell?</h3>
</div>
<%= render 'form', sell_advert: @sell_advert%>

app/views/sell_adverts/show.html.erb
<%= content_for(:title) do %>
<%= @sell_advert.title %>
<% end %>

<div class="full-container">
  <div class="half-container col-sm-6">
    <div class="" style="display: flex; justify-content: space-between; flex-direction: column; height: 500px; width: 500px;">

      <div class="title text-left">
        <h2><%= @sell_advert.title %></h2>
      </div>
      <div class="half-container" style="text-align: left">
        <p>Description:</p>
        <div class="textbox">
          <p><%= @sell_advert.description %></p>
        </div>
        <p>Condition:</p>
        <div class="textbox">
          <p><%= @sell_advert.condition %></p>
        </div>
        <p>Address:</p>
        <div class="textbox">
        <p><%= @sell_advert.address %></p>
        </div>
        <div class="textbox price">
          <h5>Price:</h5>
          <h5><%= @sell_advert.price %> <%= @sell_advert.price.symbol %> </h5>
        </div>
      </div>
     <!--  <%= link_to "Buy", new_sell_advert_order_path(@sell_advert), class: "btn-medium", id: "btn-buy" %> -->
      <div class="btn-medium" id="btn-buy">
        Buy
      </div>
      <div class="btn-medium-black" data-toggle="modal" data-target="#myModal">
        Send an email
      </div>
    </div>
  </div>
  <div class="half-container col-sm-6">
    <div class="">
      <ul  class="nav nav-pills">
        <li class="active"><a  href="#1b" data-toggle="tab">Images</a></li>
        <li><a href="#3b" data-toggle="tab">Contact</a></li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="1b">
          <% if @sell_advert.photo.filename.nil? %>
          <div class="avatar-large">
            <i class="fas fa-camera-retro"></i>
            <%= link_to "", @sell_advert, class: "advert-link" %>
          </div>
          <% else %>
            <%= cl_image_tag @sell_advert.photo, :height=>500, :width=>600, :crop=>"fill", :quality=>"auto" %>
          <% end %>
        </div>
        <div class="tab-pane" id="3b">
          <div class="title text-left title-space">
          <p>Name:</p>
          <div class="textbox-contact">
            <p><%= @sell_advert.user.first_name %> <%= @sell_advert.user.last_name %></p>
          </div>

          <p>Batch number:</p>
          <div class="textbox-contact">
            <p><%= @sell_advert.user.batch_no %></p>
          </div>

           <p>Contact details:</p>
          <div class="textbox-contact">
            <ul class="list-inline">
              <li><i class="fab fa-whatsapp"></i></li>
              <li><p><%= @sell_advert.user.phone_number %></p></li>
            </ul>
            <ul class="list-inline">
              <li><i class="far fa-envelope-open"></i></li>
              <li><p><%= @sell_advert.user.email %></p></li>
            </ul>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Send email to <%= @sell_advert.user.email %></h4>
      </div>
      <div class="modal-body">
        <%= form_tag send_contact_email_path(@sell_advert), method: :post do |f| %>
          <%= text_area_tag :message, params[:message], placeholder: "Write your message",class: "form mail-form", rows: 10, cols: 25%>
          <input type="submit" id='email-submit'>
        <% end %>
      </div>
    </div>
  </div>
</div>